---
title: "Welcome & Syllabus"
subtitle: "Lecture 01"
author: "Dr. Colin Rundel"
footer: "Sta 323 - Spring 2025"
format:
  live-revealjs:
    theme: slides.scss
    transition: fade
    slide-number: true
    self-contained: true
revealjs-plugins:
  - drop
engine: knitr
---


```{r setup}
#| message: False
#| warning: False
#| include: False
options(
  width=80
)
```


# Course Details

## Course Team

### Instrutor
* Dr. Colin Rundel 
    - [colin.rundel@duke.edu](mailto:colin.rundel@duke.edu) / 
      [cr173@duke.edu](mailto:cr173@duke.edu) /
      [rundel@gmail.com ](mailto:rundel@gmail.com)
    - Office hours: TBD (see course website)

<br/>

### TAs

* Supratik Basu
* Ziyan Wang
* Lynn Kremers


## Course website(s)

* GitHub pages - <https://sta323-sp25.github.io>
  - HTML, PDF, and qmds of Slides
  - Readings and other notes

* Canvas - <https://canvas.duke.edu/courses/51086>
  - Announcements
  - Gradebook



## Course Timetable

* Lectures (weekly) - Old Chemistry 116

  - Wednesdays, 1:25 - 2:40 pm 

  - Fridays, 1:25 - 2:40 pm 
  
  
* Labs (weekly)
  
  - Perkins LINK 087 (Classroom 3) - Tuesdays, 3:05 pm - 4:20 pm
  
  - Perkins LINK 071 (Classroom 5) - Tuesdays, 4:40 pm - 5:55 pm


## Labs

- Attendance is expected

- Opportunity to work on course assignments with TA support

- Labs will begin in Week 2 (January 21st) 



## Announcements

Will be posted on Canvas (Announcements tool)

  * email notification
  
  * also check Canvas regularly


## Grading

This course is assessed 100% on your coursework (there is no exam). We will be assessing you based on the following assignments,

<br/>

::: {.medium}
|Assignment|Type      |Value  | n   |Assigned             |
|:---------|:---------|:------|:---:|:--------------------|
|Homeworks |Team      |50%    | 5/6 | ~ Every other week  |
|Midterms  |Individual|40%    | 2   | ~ Week 6 and 14     |
|Project   |Team      |10%    | 1   | ~ Week 10           | 
:::


## Teams

* Team assignments
  + Roughly biweekly homework assignments
  + Open ended, ~5 - 15 hours of work
  + Peer evaluation after completion

* Expectations and roles:
    + Everyone is expected to contribute equal *effort*
    + Everyone is expected to understand *all* code turned in
    + Individual contribution evaluated by peer evaluation, commits, etc.



## Collaboration policy

- Only work that is clearly assigned as team work should be completed collaboratively (Homeworks + Project). 

- Individual assignments (Midterms) must be completed individually, you may not directly share or discuss answers / code with anyone other than the myself and the TAs.

- On Homeworks you should not directly share answers / code with other teams, however you are welcome to discuss the problems in general and ask for advice.


## Sharing / reusing code / AI policy

- We are aware that a huge volume of code is available on the web, and many tasks may have solutions posted.

- Unless explicitly stated otherwise, this course's policy is that you may make use of any online resources (e.g. Google, StackOverflow, etc.) but you must explicitly cite where you obtained any code you directly use or use as inspiration in your solution(s). 

- Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism, regardless of source.

- The same applies to the use of LLM like ChatGPT, Claude, or GitHub Copilot - you are welcome to make use of these tools as the basis for your solutions but you must cite the tool when using it for significant amounts of code generation.



## Academic integrity

<br/>

::: {.medium}
> To uphold the Duke Community Standard:
>
> - I will not lie, cheat, or steal in my academic endeavors;
> - I will conduct myself honorably in all my endeavors; and
> - I will act if the Standard is compromised.
:::


# Course Tools


## Accessing RStudio Workbench

To reduce friction, the preferred method is to use the department's RStudio server(s).

To access RStudio/Posit Workbench:

1.  Navigate to <https://rstudio.stat.duke.edu>
2.  Log-in with your Duke NetID and password.

::: aside
If off campus, use the VPN to create a secure connection from your computer to Duke. If you are on campus, be sure you are connected to the DukeBlue network.
:::


## DSS RStudio alternatives

If you cannot access RStudio via the DSS servers:

- Make sure you are on authenticated Duke network (e.g. DukeBlue or VPN if off campus)

- Make sure you are not using a custom DNS server

    - e.g. `1.1.1.1` or `8.8.8.8`

- Use a Docker container from Duke OIT

    1.  Go to <https://cmgr.oit.duke.edu/> and login
    2.  Select `Reserve a Container` and find a container for Sta 313
    3.  Click the link under my reservations to create your environment


## Local R + RStudio

If working locally you should make sure that your environment meets the following requirements:

* latest R (4.4.2)

* latest RStudio (2024.12.0+467)

* working git installation

* ability to create ssh keys (for GitHub authentication)

* *All* R packages updated to their latest version from CRAN

. . .

Support policy for local installs - we will try to help you troubleshoot if we can but reserve the right to tell you to use the dept server.



## GitHub

- We will be using an organization specifically to this course [github.com/sta323-sp25](https://github.com/sta323-sp25)

- All assignments will be distributed and collected via GitHub

- All of your work and your membership (enrollment) in the organization is private

- We will be distributing a survey this weekend to collection your GitHub account names 

    - Before lab you will be invited to the course organization.

- All course related repositories will be created for you


## Account names

A few suggestions on picking a GitHub username:

- Incorporate your actual name! People like to know who they're dealing with. It makes your username easier for people to guess or remember.

- Pick a username you will be comfortable revealing to your future boss.

- Shorter is better than longer.

- Be as unique as possible in as few characters as possible. In some settings GitHub auto-completes or suggests usernames.

- Make it timeless. Don't highlight your current university, employer, or place of residence.

- Avoid words laden with special meaning in programming.


## Before next week

* Create a GitHub account if you don't have one

* Complete the course survey

* Make sure you can login in to the Department's RStudio server
  <https://rstudio.stat.duke.edu>

* Setup ssh key authentication with GitHub, see <https://github.com/DukeStatSci/github_auth_guide>


